
name: Deploy Laravel 9 Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel 9
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



     - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Laravel Deploy
        uses: ngocquyhoang/laravel-deploy@laravel-custom-port
        with:
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_SERVER }}
          path: /public_html/webtest.formsliving.com/
          owner: denniapr14/FormLiving
